
title: Zuccero-site
email: www.zuccero@gmail.com
description: Everything we bake, we bake with love.
baseurl: "/zuccero" 
url: "http://zuccero.com"
destination: docs
twitter_username: di_elenkova
github_username:  di_elenkova
future: true 
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package.json
  - package-lock.json
  - .vscode
  - docs
