
title: Zuccero-site
email: di_elenkova@abv.bg
description: This is my first web site
baseurl: "/zuccero" 
url: "http://zuccero.com"
twitter_username: di_elenkova
github_username:  di_elenkova
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - scss
  - gulpfile.js
  - package.json
  - package-lock.json
  - .vscode
